### ISSUE TITLE
Add opportunity to link data product with data contract

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/dev#9]
**Is your feature request related to a problem? Please describe.**
Data products are shared and technical data contract is used in the process. That data contract is generated separately. Having a link to data contract in the data product would make sense. 

**Describe the solution you'd like**
Possibly attribute to root level? 

**Additional context**
Data Contracts

1. https://datacontract.com/
2. https://github.com/bitol-io/open-data-contract-standard

**Comment by kyyberi** [comment]
Suggested implementation approach below. This is optional object directly under the product _details_ object. 

- _Id_ (string) is needed to sepate contracts and to be able to find it in data contract management system
- _type_ (enum) defines standard used in describing the contract. Options are DCS and ODCS. 
-  _version_ defines the version of the standard used in describing the data contract
- _url_ is optional link to the data contract in data contract management system. 

**model**
```yaml
product:
  details:
     contract:
        id:      # ID, like uuid in the system managing contracts  
        type:  # this can be ODCS or DCS 
        version:   # defines the version of the above type standard used
        url:   # link to contract management system. Should be full link and go directly to agreement details. 
```

**example**
```yaml
product:
  details:
     contract:
       id: "2343e34543567e767i23" 
       type: "ODCS" 
       version: "2.2"
       url: "https://demo.datamesh-manager.com/demo834016807886/dataproducts/9bd53b1b-b51e-41a8-a757-4d33b4cde460"
```

**Comment by kyyberi** [comment]
Questions:

1. is it possible that there is need to define multiple data contracts here? 
2. should it be possible to include the data contract as YAML inline object under the contract object?

**Comment by kyyberi** [comment]
> Questions:
> 
>     1. is it possible that there is need to define multiple data contracts here?
> 
>     2. should it be possible to include the data contract as YAML inline object under the contract object?

To enable the inline YAML object mentioned in the question 2, one possibility is to add _spec_ element under which the data contract code can be added as is. That would follow the pattern we have used in data quality and SLA. 

```yaml
product:
  details:
     contract:
        id:      # ID, like uuid in the system managing contracts  
        type:  # this can be ODCS or DCS 
        version:   # defines the version of the above type standard used
        spec: # under this the YAML formatted contract can be added directly. 
    
```
